plugins {
    id 'java'
    id 'fabric-loom' version '1.13-SNAPSHOT'
}

group = 'com.rabimi.nicknamer'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.5"
    mappings "net.fabricmc:yarn:1.21.5+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.7"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.128.2+1.21.5"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 21
}

loom {
    mods {
        nicknamer {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
